// <auto-generated />
using System;
using LearnMore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnMore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906201149_AddCoachSettings")]
    partial class AddCoachSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnMore.Api.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("ReminderRepeatHours")
                        .HasColumnType("int");

                    b.Property<string>("ReminderTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UdemyAccount")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("UdemyConnected")
                        .HasColumnType("bit");

                    b.Property<string>("UdemyLastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UdemyLastSyncAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("LearnMore.Api.Models.AssessmentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AssessmentAnswers");
                });

            modelBuilder.Entity("LearnMore.Api.Models.AssessmentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JuniorCorrect")
                        .HasColumnType("int");

                    b.Property<int>("JuniorTotal")
                        .HasColumnType("int");

                    b.Property<int>("MidCorrect")
                        .HasColumnType("int");

                    b.Property<int>("MidTotal")
                        .HasColumnType("int");

                    b.Property<int>("ResultLevel")
                        .HasColumnType("int");

                    b.Property<int>("SeniorCorrect")
                        .HasColumnType("int");

                    b.Property<int>("SeniorTotal")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "TakenAt");

                    b.ToTable("AssessmentAttempts");
                });

            modelBuilder.Entity("LearnMore.Api.Models.CoachSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyProtected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CallsDate")
                        .HasColumnType("date");

                    b.Property<int>("CallsToday")
                        .HasColumnType("int");

                    b.Property<string>("KeyHint")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastCallAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("CoachSettings");
                });

            modelBuilder.Entity("LearnMore.Api.Models.DailyAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CarriedFromDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LearningItemId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("LearningItemId");

                    b.ToTable("DailyAssignments");
                });

            modelBuilder.Entity("LearnMore.Api.Models.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedLessonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Level");

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("LearnMore.Api.Models.LearningItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExplanationArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalLinksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PracticeTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Title")
                        .IsUnique();

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("LearnMore.Api.Models.PlanCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCheckpoint")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RequiredArtifacts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.ToTable("PlanCourses");
                });

            modelBuilder.Entity("LearnMore.Api.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearningItemId")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstraintsMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StakeholdersMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeError")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ProbeAnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbeQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("RunId", "StageId")
                        .IsUnique();

                    b.ToTable("ScenarioAnswers");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LlmVerdict")
                        .HasColumnType("int");

                    b.Property<bool>("QuoteUnverified")
                        .HasColumnType("bit");

                    b.Property<int>("RubricPointId")
                        .HasColumnType("int");

                    b.Property<int?>("UserVerdict")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricPointId");

                    b.HasIndex("AnswerId", "RubricPointId")
                        .IsUnique();

                    b.ToTable("ScenarioCoverage");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioRubricPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("Tag");

                    b.ToTable("ScenarioRubricPoints");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("ScenarioRuns");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InputHint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModelAnswerMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevealMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "Order")
                        .IsUnique();

                    b.ToTable("ScenarioStages");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyDayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<bool>("Studied")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Date")
                        .IsUnique();

                    b.ToTable("StudyDayLogs");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyPlanGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("StudyPlanGoals");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Date");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("LearnMore.Api.Models.UdemyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletedLectureIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompletionRatio")
                        .HasColumnType("float");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LectureCount")
                        .HasColumnType("int");

                    b.Property<int>("PendingMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PendingSince")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UdemyCourseId")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchedMinutesTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("UdemyProgress");
                });

            modelBuilder.Entity("LearnMore.Api.Models.UserStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastCompletedDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Artifact", b =>
                {
                    b.HasOne("LearnMore.Api.Models.PlanCourse", "Course")
                        .WithMany("Artifacts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnMore.Api.Models.AssessmentAnswer", b =>
                {
                    b.HasOne("LearnMore.Api.Models.AssessmentAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMore.Api.Models.InterviewQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnMore.Api.Models.AssessmentAttempt", b =>
                {
                    b.HasOne("LearnMore.Api.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnMore.Api.Models.DailyAssignment", b =>
                {
                    b.HasOne("LearnMore.Api.Models.LearningItem", "LearningItem")
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("LearnMore.Api.Models.InterviewQuestion", b =>
                {
                    b.HasOne("LearnMore.Api.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnMore.Api.Models.LearningItem", b =>
                {
                    b.HasOne("LearnMore.Api.Models.Topic", "Topic")
                        .WithMany("Items")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnMore.Api.Models.QuizQuestion", b =>
                {
                    b.HasOne("LearnMore.Api.Models.LearningItem", "LearningItem")
                        .WithMany("Quiz")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioAnswer", b =>
                {
                    b.HasOne("LearnMore.Api.Models.ScenarioRun", "Run")
                        .WithMany("Answers")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMore.Api.Models.ScenarioStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioCoverage", b =>
                {
                    b.HasOne("LearnMore.Api.Models.ScenarioAnswer", "Answer")
                        .WithMany("Coverage")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMore.Api.Models.ScenarioRubricPoint", "RubricPoint")
                        .WithMany()
                        .HasForeignKey("RubricPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("RubricPoint");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioRubricPoint", b =>
                {
                    b.HasOne("LearnMore.Api.Models.ScenarioStage", "Stage")
                        .WithMany("RubricPoints")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioRun", b =>
                {
                    b.HasOne("LearnMore.Api.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioStage", b =>
                {
                    b.HasOne("LearnMore.Api.Models.Scenario", "Scenario")
                        .WithMany("Stages")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyDayLog", b =>
                {
                    b.HasOne("LearnMore.Api.Models.StudyPlan", "Plan")
                        .WithMany("DayLogs")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyPlanGoal", b =>
                {
                    b.HasOne("LearnMore.Api.Models.StudyPlan", "Plan")
                        .WithMany("Goals")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudySession", b =>
                {
                    b.HasOne("LearnMore.Api.Models.PlanCourse", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnMore.Api.Models.UdemyProgress", b =>
                {
                    b.HasOne("LearnMore.Api.Models.PlanCourse", "Course")
                        .WithOne()
                        .HasForeignKey("LearnMore.Api.Models.UdemyProgress", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnMore.Api.Models.AssessmentAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LearnMore.Api.Models.LearningItem", b =>
                {
                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LearnMore.Api.Models.PlanCourse", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Scenario", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioAnswer", b =>
                {
                    b.Navigation("Coverage");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioRun", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LearnMore.Api.Models.ScenarioStage", b =>
                {
                    b.Navigation("RubricPoints");
                });

            modelBuilder.Entity("LearnMore.Api.Models.StudyPlan", b =>
                {
                    b.Navigation("DayLogs");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("LearnMore.Api.Models.Topic", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
